[package]
name = "query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
serde_json = "1.0.127"
serde_with = "3.9.0"
serde = { version = "1.0.209", features = ["derive"] }
